CbvProject/CbvApp/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    # path('',views.CBView.as_view()),
    path('', views.IndexView.as_view())

]

CbvProject/CbvProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('ListDetailViewApp.urls')),
    path('ListDetailViewApp/',include('ListDetailViewApp.urls',namespace='ListDetailViewApp')),
    path('admin/', admin.site.urls),
]

CbvProject/ListDetailViewApp/urls.py
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name = 'ListDetailViewApp'

#the below are the installed apps in the project
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('list',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),

]

CbvProject/CbvApp/models.py
from django.db import models

# Create your models here.

CbvProject/ListDetailViewApp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    Principal = models.CharField(max_length=256)
    Location = models.CharField(max_length=256)
    def __str__(self):
        return self.name
    def get_absolute_url(self):     # after creating a view,goes to detail page
        return reverse("ListDetailViewApp:list")

class Students(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE,related_name='students')
    def __str__(self):
        return self.name

CbvProject/CbvApp/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView
from django.http import HttpResponse

# Create your views here.
# class CBView(View):                            # Class Based View
#     def get(self,request):
#         return HttpResponse('Class Based Views are Cool!')

class IndexView(TemplateView):                 # Template View
    template_name = 'index1.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = "BASIC INJECTION"
        return context

CbvProject/ListDetailViewApp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View,ListView,DetailView,
                                   TemplateView,CreateView,
                                    UpdateView,DeleteView)
from . import models

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'ListDetailViewApp/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','Principal','Location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','Principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("ListDetailViewApp:list")

CbvProject/ListDetailViewApp/templates/ListDetailViewApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu"
          crossorigin="anonymous">
</head>
<body>
    <nav class="nav navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'ListDetailViewApp:list' %}">Schools</a></li>
        </ul>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

CbvProject/ListDetailViewApp/templates/ListDetailViewApp/school_confirm_delete.html
{% extends 'ListDetailViewApp/base.html' %}

{% block body_block %}

    <h2>Delete {{ school.name }} ?</h2>
    <form method="post">
        {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'ListDetailViewApp:list' %}">Cancel</a>
    </form>

{% endblock %}

CbvProject/ListDetailViewApp/templates/ListDetailViewApp/school_detail.html
{% extends 'ListDetailViewApp/base.html' %}

{% block body_block %}
    <div class="jumbotron">

    <h2>Welcome to the School Detail Page</h2>
    <h3>School Details:</h3>
    <p>Name : {{ school_detail.name }}</p>
    <p>Principal : {{school_detail.Principal }}</p>
    <p>Location : {{ school_detail.Location }}</p>

    <h3>Student Details:</h3>
    {% for student in school_detail.students.all %}
    <p>{{ student.name }} who is {{ student.age }} years old.</p>
    {% endfor %}

    </div>

    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'ListDetailViewApp:update' pk=school_detail.pk %}">Update</a></p>
    </div>
{% endblock %}

CbvProject/ListDetailViewApp/templates/ListDetailViewApp/school_form.html
{% extends 'ListDetailViewApp/base.html' %}
{% block body_block %}

    <h1>Create School</h1>
<!--        {% if not form.instance.pk %}-->
<!--        Create School-->
<!--        {% else %}-->
<!--        Update School-->
<!--        {% endif %}-->
<!--    </h1>-->

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-warning" value="Submit">
    </form>

{% endblock %}

CbvProject/ListDetailViewApp/templates/ListDetailViewApp/school_list.html
{% extends 'ListDetailViewApp/base.html' %}

{% block body_block %}

    <h2>Welcome to the list of all schools</h2>
    <ol>
        {% for school in schools %}
        <h3><li><a href="{{ school.id }}" >{{ school.name }}</a></li></h3>
        {% endfor %}
    </ol>

{% endblock %}

CbvProject/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu"
          crossorigin="anonymous">
</head>
<body>
    <nav class="nav navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'ListDetailViewApp:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

CbvProject/templates/home1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu"
          crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

CbvProject/templates/index.html
{% extends 'home.html' %}

{% block body_block %}

    <h2>Home Page!</h2>

{% endblock %}

CbvProject/templates/index1.html
{% extends 'home1.html' %}
{% block body_block %}

    <h2>Welcome to Template Views!</h2>
    <h3>Injected : {{ injectme }}</h3>
{% endblock %}